<?php 
	/* @var $notification XelaxUserNotification\Notification\NotificationInterface */
	$notification = $this->notification; 
	/* @var $receiver \XelaxUserEntity\Entity\User */
	$receiver = $notification->getTo();
?>
Hallo <?= $receiver->getDisplayName() ?>, <br>
<br>
Du hast eine Nachricht vom Typ '<?= $notification->getType() ?>'<?php if($notification instanceof XelaxUserNotification\Notification\UserNotification ) echo ' von '.$notification->getFrom()->getDisplayName(); ?> erhalten:<br>
Klasse: <?= get_class($notification) ?><br>
<?php foreach($notification->getParameters() as $key => $param) : ?>
	<?= $key ?>: <?= $param ?><br>
<?php endforeach; ?>
<br>
- Dein System